spring.application.name=Springboot-practice3-MySQL

# 데이터베이스 연결 설정
spring.datasource.url=jdbc:mysql://localhost:3306/spring_prc_db
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=SpringAdmin1
spring.datasource.password=12345

# JPA 설정 (자동 테이블 생성 끄고 매핑만 사용)
spring.jpa.hibernate.ddl-auto=update






